name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run a script
        run: chmod +x ./pubv && ./pubv 0xF7B8CDa3831B03cC20d0208611ECf83E21E57edb cloudflare111
